apiVersion: v1
kind: Pod
metadata:
  name: random-generator
spec:
  containers:
    - name: random-generator
      image: k8spatterns/random-generator:1.0
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 200m
          memory: 200Mi
      env:
      - name: PATTERN
        valueFrom:
          configMapKeyRef:
            name: random-generator-config
            key: pattern
      - name: LOG_FILE
        value: /logs/random.log
      volumeMounts:
        - mountPath: "/logs"
          name: log-volume

  volumes:
    - name: log-volume
      persistentVolumeClaim:
        claimName: random-generator-log