apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongo-storage-class
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/gce-pd