apiVersion: v1
kind: Pod
metadata:
  name: random-generator
  labels:
    app: random-generator
spec:
  containers:
    - name: random-generator
      image: k8spatterns/random-generator:1.0
      resources:
        requests:
          cpu: "200m"
          memory: "200Mi"
        limits:
          cpu: "200m"
          memory: "200Mi"
      env:
      - name: LOG_FILE
        value: /tmp/random.log
      - name: PATTERN
        valueFrom:
          configMapKeyRef:
            name: random-generator-config
            key: pattern
      - name: SEED
        valueFrom:
          secretKeyRef:
            name: random-generator-secret
            key: seed