apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    project: k8spatterns
    pattern: ImmutableConfiguration
spec:
  selector:
    pattern: ImmutableConfiguration
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: NodePort