apiVersion: v1
kind: Pod
metadata:
  name: web-app
  labels:
    name: web-app
spec:
  containers:
  - name: web-app
    image: docker.io/centos/httpd
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - name: git
        mountPath: /var/www/html
  - name: poll
    image: axeclbr/git
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
    volumeMounts:
      - name: git
        mountPath: /var/lib/data
    env:
    - name: GIT_REPO
      value: "https://github.com/mdn/beginner-html-site-scripted"
    command:
      - "sh"
      - "-c"
      - "git clone $(GIT_REPO) . && watch -n 600 git pull"
    workingDir: /var/lib/data
  volumes:
    - name: git
      emptyDir: {}
