apiVersion: v1
kind: Service
metadata:
  name: random-generator
spec:
  selector:
    app: random-generator
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: NodePort

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: random-generator
  labels:
    name: random-generator
spec:
  backend:
    serviceName: random-generator
    servicePort: 8080
