apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    svc: headless
spec:
  hostname: first-pod
  subdomain: headless
  containers:
  - name: container
    image: kubetm/app
    ports:
    - containerPort: 8080
  