apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    svc: headless
spec:
  hostname: second-pod
  subdomain: headless
  containers:
  - name: container
    image: kubetm/app
    ports:
      - containerPort: 8080