apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: inflearn-cluster-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: inflearn-cluster-admin
subjects:
  - kind: ServiceAccount
    name: inflearn-sa
    namespace: inflearn