apiVersion: v1
kind: Pod
metadata:
  name: www
  labels:
    app: www
spec:
  initContainers:
    - name: download
      image: axeclbr/git
      command:
        - "git"
        - "clone"
        - "https://github.com/mdn/beginner-html-site-scripted"
        - "/var/lib/data"
      volumeMounts:
      - mountPath: /var/lib/data
        name: source

  containers:
  - name: run
    image: docker.io/centos/httpd
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /var/www/html
        name: source
  volumes:
    - name: source
      emptyDir: {} 
        