apiVersion: v1
kind: Pod
metadata:
  name: nod-affinity
spec:
  containers:
  - name: random-generator
    image: k8spatterns/random-generator:1.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: numberCores
                operator: Gt
                values: ["3"]
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 10
          preference:
            matchFields:
              - key: metadata.name
                operator: NotIn
                values: ["minikube"]