apiVersion: v1
kind: Pod
metadata:
  name: random-generator
  labels:
    name: random-generator
spec:
  containers:
  - name: random-generator
    image: k8spatterns/random-generator:1.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
    - name: LOG_URL
      value: http://localhost:9009
    ports:
      - containerPort: 8080
        protocol: TCP
  - name: ambassador
    image: k8spatterns/random-generator-log-ambassador
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
        

