apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Mi
  storageClassName: standard    
  hostPath:
    path: /tmp/example/1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-2
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Mi
  storageClassName: standard    
  hostPath:
    path: /tmp/example/2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-3
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Mi
  storageClassName: standard    
  hostPath:
    path: /tmp/example/3