apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rg
spec:
  selector:
    matchLabels:
      app: random-generator
  serviceName: random-generator
  replicas: 2
  template:
    metadata:
      labels:
        app: random-generator
    spec:
      containers:
      - name: random-generator
        image: k8spatterns/random-generator:1.0
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: logs
          mountPath: /opt/logs
  volumeClaimTemplates:
  - metadata:
      name: logs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Mi
