apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      limits:
        cpu: "200m"
        memory: "128Mi"
    ports:
      - containerPort: 80
  restartPolicy: Always
status: {}
