apiVersion: v1
kind: PersistentVolume
metadata:
  name: example
spec:
  accessModes:
  - "ReadWriteOnce"
  capacity:
    storage: 20Mi
  storageClassName: standard
  hostPath:
    path: /example
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: random-generator-log
spec:
  accessModes:
  - "ReadWriteOnce"
  resources:
    requests:
      storage: 20Mi
  volumeName: example