apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
spec:
  accessMode:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      volume: my-volume