apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-hostport
spec:
  selector:
    matchLabels:
      type: app
  template:
    metadata:
      labels:
        type: app
    spec:
      containers:
        - name: container
          image: kubetm/app
          ports:
          - containerPort: 8080
            hostPort: 18080