apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-generator
spec:
  replicas: 6
  strategy:
    type: recreate
  selector:
    matchLabels:
      app: random-generator
  template:
    metadata:
      labels:
        app: random-generator
    spec:
      containers:
      - name: random-generator
        image: k8spatterns/random-generator:1.0
        env:
        - name: DELAY_STARTUP
          value: "5"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
        readinessProbe:
          exec:
            command:
              - "stat"
              - "/opt/random-generator/ready"
        tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080
          protocol: TCP
