apiVersion: v1
kind: Pod
metadata:
  name: random-generator
  labels:
    name: random-generator
spec:
  containers:
  - name: random-generator
    image: k8spatterns/random-generator:1.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
    env:
    - name: SPRING_CONFIG_LOCATION
      value: /config/application.properties
    volumeMounts:
      - name: config-volume
        mountPath: /config  
  volumes:
    - name: config-volume
      configMap:
        name: random-generator-config
