apiVersion: v1
kind: Pod
metadata:
  name: random-generator
  labels:
    app: random-generator
spec:
  containers:
  - name: random-generator
    image: k8spatterns/random-generator:1.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    envFrom:
      - configMapRef:
          name: random-generator-config
        prefix: CONFIG_
