apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
metadata:
  name: random-generator
spec:
  updatePolicy:
    updateMode: Recreate
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: random-generator