apiVersion: v1
kind: Service
metadata:
  name: random-generator
spec:
  selector:
    app: random-generator
  ports:
  - name: random-generator
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: promethues
    port: 9889
    targetPort: 9889
    protocol: TCP
  type: NodePort
