apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random-generator
  template:
    metadata:
      labels:
        app: random-generator
    spec:
      containers:
      - name: random-generator
        image: safecornerscoffee/random-generator:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: DELAY_STARTUP
          value: "20"
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
        readinessProbe:
          exec:
            command: ["stat", "/opt/random-generator-ready"]

            
